### ISSUE TITLE
java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by ennerf** [BlueGoliath/Envious-FX#2]
I downloaded the release version, ran `./run` from powershell in the bin directory, and got the following error:

**Output**

```
WARNING: Unknown module: org.goliath.bindings.gamemode specified to --enable-native-access
WARNING: Unknown module: org.goliath.bindings.nvxctrl specified to --enable-native-access
WARNING: Unknown module: org.goliath.bindings.x specified to --enable-native-access
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetTargetFanSpeed
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetGpcClkMinMaxVfOffset
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetMemClkVfOffset
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetMemClkMinMaxVfOffset
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceSetMemClkVfOffset
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetPowerMode
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetSupportedPowerModes
Oct 12, 2022 12:07:52 PM org.goliath.crosspoint.interfaces.NativeLibrary getSymbolOrStub
WARNING: generating stub for missing symbol nvmlDeviceGetPowerMode
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Unknown Source)
        at org.goliath.envious.fx.app@1/org.goliath.envious.fx.app.monitoring.MonitoringContentPane.<init>(Unknown Source)
        at org.goliath.envious.fx.app@1/org.goliath.envious.fx.app.content.monitoring.PCIeContentItem.<init>(Unknown Source)
        at org.goliath.envious.fx.app@1/org.goliath.envious.fx.app.content.MonitoringContentItem.<init>(Unknown Source)
        at org.goliath.envious.fx.app@1/org.goliath.envious.fx.app.MainAppContent.<init>(Unknown Source)
        at org.goliath.envious.fx.app@1/org.goliath.envious.fx.app.AppRoot.<init>(Unknown Source)
        at org.goliath.envious.fx.app@1/org.goliath.envious.fx.app.GoliathEnviousFX.start(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
        at javafx.graphics@19/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics@19/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics@19/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Exception running application org.goliath.envious.fx.app.GoliathEnviousFX
```

**NVIDIA System Information**

```
[Display]
Operating System:	Windows 10 Enterprise, 64-bit
DirectX version:	12.0 
GPU processor:		NVIDIA GeForce RTX 2060
Driver version:		516.94
Driver Type:		DCH
Direct3D feature level:	12_1
CUDA Cores:		1920 
Core clock:		1755 MHz 
Memory data rate:	14.00 Gbps
Memory interface:	192-bit 
Memory bandwidth:	336.05 GB/s
Total available graphics memory:	22484 MB
Dedicated video memory:	6144 MB GDDR6
System video memory:	0 MB
Shared system memory:	16340 MB
Video BIOS version:	90.06.3F.00.E8
IRQ:			Not used
Bus:			PCI Express x16 Gen3
Device Id:		10DE 1F08 3FC11458
Part Number:		G161 0042

[Components]

nvui.dll		8.17.15.1694		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.15.1694		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.15.1694		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.15.1694		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.15.1694		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		31.0.15.1694		NVIDIA Workstation Server
nvWSS.dll		31.0.15.1694		NVIDIA Workstation Server
nvViTvSR.dll		31.0.15.1694		NVIDIA Video Server
nvViTvS.dll		31.0.15.1694		NVIDIA Video Server
nvLicensingS.dll	6.14.15.1694		NVIDIA Licensing Server
nvDevToolSR.dll		31.0.15.1694		NVIDIA Licensing Server
nvDevToolS.dll		31.0.15.1694		NVIDIA 3D Settings Server
nvDispSR.dll		31.0.15.1694		NVIDIA Display Server
nvDispS.dll		31.0.15.1694		NVIDIA Display Server
PhysX			09.21.0713		NVIDIA PhysX
NVCUDA64.DLL		31.0.15.1694		NVIDIA CUDA 11.7.101 driver
nvGameSR.dll		31.0.15.1694		NVIDIA 3D Settings Server
nvGameS.dll		31.0.15.1694		NVIDIA 3D Settings Server
```

**Comment by BlueGoliath** [comment]
I know what this is. Thought it was hardware specific or related to me running a built-from-source JDK at the time but I guess not. Maybe it's a bug in NVML. I don't really know. 

You should be able to bypass it by setting the number of worker threads to something lower. In bin, create a folder called "settings", create a "envious.fx.cfg", and then add:

`envious.fx.threads=4`

Hope this works. Thanks for reporting it!

**Comment by BlueGoliath** [comment]
If that worked for you, could you try bumping the thread count until it crashes and let me know how high it will work for you? Thanks.

**Comment by BlueGoliath** [comment]
Just noticed an issue with the power mode set function that I overlooked. Going to push a minor update. It won't matter for your Turing GPU but it will for Ada Lovelace.

**Comment by ennerf** [comment]
Setting the thread number to a value from 0 to 6 makes it work. I'm running a 12 core / 24 thread Ryzen 9 3900x.

**Comment by BlueGoliath** [comment]
Thanks. On my Windows PC I can go to 14 threads before crashing. The computer only has 4 cores so the number of actual cores is irrelevant it seems.
